const state={step:1,model:"iPhone 12",storage:"64GB",battery:100,functions:{},fnIndex:0,screenFunction:"Alles functioneert",screen:"Geen barsten, beschadigingen of diepe bekrassingen",screenCondition:"Geen gebruikssporen",sides:"Geen gebruikssporen",back:"Geen gebruikssporen"};
const models=["iPhone 17 Pro Max","iPhone 17 Pro","iPhone 17","iPhone 16 Pro Max","iPhone 16 Pro","iPhone 16","iPhone 15 Pro Max","iPhone 15 Pro","iPhone 15","iPhone 14 Pro Max","iPhone 14 Pro","iPhone 14","iPhone 13 Pro Max","iPhone 13 Pro","iPhone 13","iPhone 12 Pro Max","iPhone 12 Pro","iPhone 12","iPhone 11 Pro Max","iPhone 11 Pro","iPhone 11"];
const modelPrices={"iPhone 11":85,"iPhone 11 Pro":110,"iPhone 11 Pro Max":125,"iPhone 12 mini":90,"iPhone 12":100,"iPhone 12 Pro":120,"iPhone 12 Pro Max":140,"iPhone 13 mini":110,"iPhone 13":125,"iPhone 13 Pro":155,"iPhone 13 Pro Max":180,"iPhone 14":165,"iPhone 14 Plus":185,"iPhone 14 Pro":210,"iPhone 14 Pro Max":240,"iPhone 15":235,"iPhone 15 Plus":260,"iPhone 15 Pro":295,"iPhone 15 Pro Max":335,"iPhone 16":305,"iPhone 16 Plus":335,"iPhone 16 Pro":375,"iPhone 16 Pro Max":430,"iPhone 17":395,"iPhone 17 Air":420,"iPhone 17 Pro":465,"iPhone 17 Pro Max":530};
const home=document.getElementById("homePage"),trade=document.getElementById("tradePage"),app=document.getElementById("app"),priceEl=document.getElementById("price");
function euro(n){return "€ "+n.toFixed(2).replace(".",",")}
function price(){let p=modelPrices[state.model]||100;const mult={"64GB":.95,"128GB":1,"256GB":1.12,"512GB":1.28,"1TB":1.4};p*=mult[state.storage]||1;if(state.battery<80)p-=25;else if(state.battery<90)p-=12;Object.values(state.functions).forEach(v=>{if(v==="NEE")p-=20});if(state.screen==="Gebarsten")p-=55;if(state.screen==="Beschadigd")p-=30;if(state.screen==="Zwaar bekrast")p-=20;if(state.screenCondition==="Zichtbare slijtage")p-=15;if(state.screenCondition==="Sommige sporen van slijtage")p-=7;if(state.sides==="Beschadigd")p-=35;if(state.sides==="Zichtbare slijtage")p-=18;if(state.sides==="Sommige sporen van slijtage")p-=8;if(state.back==="Beschadigd")p-=40;if(state.back==="Zichtbare slijtage")p-=20;if(state.back==="Sommige sporen van slijtage")p-=8;return Math.max(0,Math.round(p))}
const modelImages={
"iPhone 11":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11.jpg",
"iPhone 11 Pro":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-11-pro.jpg",
"iPhone 11 Pro Max":"https://www.vhv.rs/dpng/d/517-5176778_apple-iphone-11-png-iphone-11-pro-max.png",
"iPhone 12 mini":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-mini.jpg",
"iPhone 12":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12.jpg",
"iPhone 12 Pro":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-12-pro.jpg",
"iPhone 12 Pro Max":"https://assets.stickpng.com/images/61d2f9ce92b57c0004c64749.png",
"iPhone 13 mini":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-mini.jpg",
"iPhone 13":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13.jpg",
"iPhone 13 Pro":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro.jpg",
"iPhone 13 Pro Max":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-13-pro-max.jpg",
"iPhone 14":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14.jpg",
"iPhone 14 Plus":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-plus.jpg",
"iPhone 14 Pro":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-14-pro.jpg",
"iPhone 14 Pro Max":"https://www.apple-juice.com/Resources/Images/png/iPhones/14%20Pro%20Max%20no%20bg.png",
"iPhone 15":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15.jpg",
"iPhone 15 Plus":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-plus.jpg",
"iPhone 15 Pro":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro.jpg",
"iPhone 15 Pro Max":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-15-pro-max.jpg",
"iPhone 16":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16.jpg",
"iPhone 16 Plus":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-plus.jpg",
"iPhone 16 Pro":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro.jpg",
"iPhone 16 Pro Max":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-16-pro-max.jpg",
"iPhone 17":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-17.jpg",
"iPhone 17 Air":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-air.jpg",
"iPhone 17 Pro":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-17-pro.jpg",
"iPhone 17 Pro Max":"https://fdn2.gsmarena.com/vv/bigpic/apple-iphone-17-pro-max.jpg"
};
function phoneArt(model){const src=modelImages[model]||modelImages["iPhone 15"];return `<div class="phone-photo"><img src="${src}" alt="${model}" loading="lazy" onerror="this.parentElement.classList.add('photo-fallback');this.remove()"><div class="phone-art-fallback"><div class="screen-art"></div></div></div>`}
function renderModels(filter=""){const grid=document.getElementById("modelGrid");if(!grid)return;grid.innerHTML=models.filter(m=>m.toLowerCase().includes(filter.toLowerCase())).map((m)=>`<article class="model-card" data-model="${m}"><h3>${m}</h3><p>Schatting tot ${euro(modelPrices[m]||100)}</p>${phoneArt(m)}</article>`).join("");grid.querySelectorAll(".model-card").forEach(card=>card.onclick=()=>startTrade(card.dataset.model))}
function startTrade(model){state.model=model;state.step=1;state.fnIndex=0;state.functions={};home.hidden=true;trade.hidden=false;document.querySelector(".trade-page .progress-wrap").style.display="flex";document.querySelector(".trade-page .topbar").innerHTML='<a class="trade-logo" href="#" id="homeBack">m<span style="color:var(--green)">o</span>bix</a><a href="login.html" class="login-link">Inloggen</a><div class="step-label" id="stepLabel">1/8</div>';document.getElementById("homeBack").onclick=e=>{e.preventDefault();showHome()};renderTrade();window.scrollTo({top:0,behavior:"smooth"})}
function showHome(){trade.hidden=true;home.hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
function option(title,desc,key,val){const selected=state[key]===val;return `<label class="option ${selected?"selected":""}"><input type="radio" name="${key}" ${selected?"checked":""} data-key="${key}" data-val="${val}"><span><span class="option-title">${title}</span>${desc?`<div class="option-desc">${desc}</div>`:""}</span></label>`}
function options(list,key){return `<div class="options">${list.map(x=>option(x[0],x[1]||"",key,x[0])).join("")}</div>`}
function side(){const rows=[["Model",state.model+" "+state.storage],["Batterijconditie",state.battery+"%"]];if(state.step>=3)rows.push(["Functiecheck",Object.keys(state.functions).length?"Gecontroleerd":"—"]);if(state.step>=4)rows.push(["Schermfunctionaliteit",state.screenFunction]);if(state.step>=5)rows.push(["Scherm",state.screen]);if(state.step>=6)rows.push(["Schermconditie",state.screenCondition]);if(state.step>=7)rows.push(["Zijkantenconditie",state.sides]);if(state.step>=8)rows.push(["Achterkant",state.back]);document.getElementById("sideSummary").innerHTML=rows.map(r=>`<div class="summary-row"><span>${r[0]}</span><b>${r[1]}</b></div>`).join("")}
function renderTrade(){document.getElementById("stepLabel").textContent=`${state.step}/8`;document.getElementById("stepLabel2").textContent=`${state.step}/8`;document.getElementById("progressBar").style.width=(state.step/8*100)+"%";document.getElementById("backBtn").style.visibility=state.step===1?"hidden":"visible";priceEl.textContent=euro(price());side();
if(state.step===1){let stores;if(["iPhone 11","iPhone 11 Pro","iPhone 12 mini","iPhone 12"].includes(state.model))stores=["64GB","128GB","256GB"];else if(["iPhone 11 Pro Max","iPhone 12 Pro","iPhone 13 mini","iPhone 13","iPhone 12 Pro Max","iPhone 13 Pro"].includes(state.model))stores=["128GB","256GB","512GB"];else if(["iPhone 13 Pro Max","iPhone 14","iPhone 14 Plus","iPhone 15","iPhone 15 Plus","iPhone 16","iPhone 16 Plus"].includes(state.model))stores=["128GB","256GB","512GB"];else stores=["256GB","512GB","1TB"];if(!stores.includes(state.storage))state.storage=stores[0];app.innerHTML=`<h1>Opslagcapaciteit</h1><p class="subtitle">Controleer de opslaggrootte van het toestel</p><div class="info">ⓘ Te vinden in <b>Instellingen → Algemeen → Info</b></div>${options(stores.map(x=>[x]),"storage")}<button class="primary" id="next">Doorgaan →</button>`}
else if(state.step===2){app.innerHTML=`<h1>Batterijconditie</h1><p class="subtitle">Controleer de maximale capaciteit van de batterij</p><div class="info">ⓘ Ga naar <b>Instellingen → Batterij → Batterijconditie en opladen</b></div><div class="field"><input id="battery" type="number" min="1" max="100" value="${state.battery}" placeholder="Bijv. 87"><span>%</span></div><button class="primary" id="next">Doorgaan →</button>`}
else if(state.step===3){const done=["iPhone gaat aan","Netwerkverbinding / IMEI","Face ID","Frontcamera","Luidspreker"];const idx=state.fnIndex||0;app.innerHTML=`<h1>Functiecheck</h1><p class="subtitle">Controleer de functionaliteit van je toestel</p><div class="done-list">${done.slice(0,idx).map(x=>`<div class="done"><span>${x}</span><span>✓</span></div>`).join("")}</div><div class="function-box"><div class="function-num">${idx+1}/5</div><div class="function-title">${done[idx]}</div><div class="info function-info" style="margin-top:14px">${idx===1?`Kan je iPhone verbinden met een netwerk?<br><br><b>Toets *#06#.</b> Verschijnt er geen IMEI? Kies nee.<br><br><code>*#06#</code>`:`ⓘ Controleer of deze functie goed werkt op je iPhone.`}</div><div class="checks"><button data-answer="JA">JA</button><button data-answer="NEE">NEE</button></div></div>`}
else if(state.step===4){app.innerHTML=`<h1>Schermfunctionaliteit</h1><p class="subtitle">Controleer op heldere plekken, dode pixels of lijnen/ingebrand beeld.</p>${options([["Heldere plekken"],["Dode pixels"],["Lijnen/ingebrand beeld"],["Alles functioneert"]],"screenFunction")}<button class="primary" id="next">Doorgaan →</button>`}
else if(state.step===5){app.innerHTML=`<h1>Scherm</h1><p class="subtitle">Controleer het scherm op barsten, beschadigingen en diepe krassen.</p>${options([["Gebarsten"],["Beschadigd"],["Zwaar bekrast"],["Geen barsten, beschadigingen of diepe bekrassingen"]],"screen")}<button class="primary" id="next">Doorgaan →</button>`}
else{const data={6:["Schermconditie","Inspecteer het scherm op krassen en slijtage",["Zichtbare slijtage","Sommige sporen van slijtage","Minimale tekenen van slijtage","Geen gebruikssporen"],"screenCondition"],7:["Zijkantenconditie","Inspecteer de zijkanten op krassen en slijtage.",["Beschadigd","Zichtbare slijtage","Sommige sporen van slijtage","Minimale tekenen van slijtage","Geen gebruikssporen"],"sides"],8:["Staat van de achterkant","Inspecteer de achterkant op krassen en slijtage.",["Beschadigd","Zichtbare slijtage","Sommige sporen van slijtage","Minimale tekenen van slijtage","Geen gebruikssporen"],"back"]};const d=data[state.step];app.innerHTML=`<h1>${d[0]}</h1><p class="subtitle">${d[1]}</p>${options(d[2].map(x=>[x]),d[3])}<button class="primary" id="next">${state.step===8?"Bekijk prijs →":"Doorgaan →"}</button>`}bindTrade()}
function bindTrade(){document.querySelectorAll("input[type=radio]").forEach(el=>el.addEventListener("change",e=>{state[e.target.dataset.key]=e.target.dataset.val;renderTrade()}));const b=document.getElementById("battery");if(b)b.addEventListener("input",e=>{state.battery=Math.min(100,Math.max(1,+e.target.value||1));priceEl.textContent=euro(price());side()});document.querySelectorAll("[data-answer]").forEach(btn=>btn.onclick=()=>{state.functions["f"+(state.fnIndex||0)]=btn.dataset.answer;state.fnIndex=(state.fnIndex||0)+1;if(state.fnIndex>=5){state.step=4;state.fnIndex=0}renderTrade()});const next=document.getElementById("next");if(next)next.onclick=()=>{if(state.step<8){state.step++;renderTrade()}else showResult()}}
function showResult(){const p=price();document.querySelector(".trade-page .progress-wrap").style.display="none";document.querySelector(".trade-page .topbar").innerHTML='<a class="trade-logo" href="#" id="homeBack">Mobix</a><div>Samenvatting</div>';app.innerHTML=`<div class="result"><div class="result-phone">${phoneArt(state.model)}</div><h1>Jouw geschatte prijs</h1><div class="result-model">${state.model} · ${state.storage}</div><div class="big">${euro(p)}</div><div class="info">Je schatting is 14 dagen geldig.</div><div class="sell-options"><div class="sell-card"><h3>🏪 Verkopen in de winkel</h3><p>Laat je toestel controleren en ontvang je definitieve prijs.</p></div><div class="sell-card"><h3>📦 Verkopen via de post</h3><p>Gratis verzending en controle van je toestel.</p></div></div><div class="result-actions"><button class="primary" id="newCheck">Andere iPhone controleren</button><button class="secondary home-return" onclick="showHome()">← Terug naar home</button></div></div>`;document.getElementById("homeBack").onclick=e=>{e.preventDefault();showHome()};document.getElementById("newCheck").onclick=()=>{showHome();setTimeout(()=>document.getElementById("deals")?.scrollIntoView({behavior:"smooth"}),50)}}
document.getElementById("backBtn").onclick=()=>{if(state.step>1){state.step--;renderTrade()}};document.getElementById("homeBack").onclick=e=>{e.preventDefault();showHome()};document.getElementById("navSell").onclick=e=>{e.preventDefault();startTrade(state.model)};document.getElementById("modelSearch").addEventListener("input",e=>renderModels(e.target.value));renderModels();
